site_name: Link:UP
site_description: Link:UP 2026
copyright: Link:UP 2026
repo_url: https://github.com/marrold/linkup-website
repo_name: Improve this website
theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.svg
  icon:
    logo: material/transit-connection-variant
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/monitor
        name: Turn off CRT effect
    - scheme: default
      primary: black
      toggle:
        icon: material/monitor-off
        name: Turn on CRT effect
  features:
    - toc.integrate
    - navigation.top
    - navigation.indexes

plugins: []

markdown_extensions:
  - attr_list
  - tables
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/extra.css

nav:
  - About: index.md
  - Info: info.md
  - Network & Services: network.md
  - Help Us: help-us.md
  - Contact: contact.md

extra:
  generator: false
